// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Description string `json:"description" `
	Status      string `json:"status"`
}

type Todo struct {
	ID          string `json:"id" bson:"_id"`
	Description string `json:"description"`
	Status      bool   `json:"status"`
}
